### Seed users
POST http://localhost:4000/api/admin/seed


### Create user
POST http://localhost:4000/api/admin
Content-Type: application/json

{
    "username": "monica",
    "password": "monicaONE",
    "emailAddress": "monica@ameliorate.com"
}

### Read users
GET http://localhost:4000/api/admin

### Update user

### Delete all users
DELETE http://localhost:4000/api/admin/delete/all